# Generated by Django 2.1 on 2018-02-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.PositiveIntegerField()),
                ('revision', models.CharField(max_length=40)),
                ('foo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='push',
            unique_together={('repository', 'foo'), ('repository', 'revision')},
        ),
    ]
